// Code generated by "stringer -type=RuntimeType"; DO NOT EDIT.

package clauses

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[noRuntime-0]
	_ = x[legacy-1]
	_ = x[pipelined-2]
	_ = x[slotted-3]
	_ = x[parallel-4]
	_ = x[interpreted-5]
}

const _RuntimeType_name = "noRuntimelegacypipelinedslottedparallelinterpreted"

var _RuntimeType_index = [...]uint8{0, 9, 15, 24, 31, 39, 50}

func (i RuntimeType) String() string {
	if i < 0 || i >= RuntimeType(len(_RuntimeType_index)-1) {
		return "RuntimeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuntimeType_name[_RuntimeType_index[i]:_RuntimeType_index[i+1]]
}
