name: docker-test-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed Dockerfiles
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: "dockerfiles/**"
        since_last_remote_commit: true 

    - name: Build changed Dockerfiles
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # Redirect output to /dev/null, thus not saving the image
          docker build -f $file -t image --output type=tar,dest=/dev/null .
        done
