name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    # TODO: Remove once repo is public
    env:
      GOPRIVATE: github.com/Anon10214/*
    steps:
      - uses: actions/checkout@v3

      - name: Spin up containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./integration/docker-compose.ci.yml"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Test
        run: GOEXPERIMENT=nocoverageredesign go test -v -tags=integration -coverpkg=./... -coverprofile=coverage.out ./...
